title: Researcher
url: "https://indrateja25.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/indrateja25"
footer_text: "My Personal Resume"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resu"
 - name: "Contact"
   link: "contact"
